### ISSUE TITLE
BUG: Fixing the dropdown menu

### ISSUE THREAD

**Issue by Aryan-81** [Aryan-81/Astria-Za_web#4]
Bring up the drop down menu option for year and reduce the width of the option box .
(Making the drop down menu responsive)

![image](https://github.com/Aryan-81/Astria-Za_web/assets/131597580/af2484dd-e7fe-4c58-9507-f64c810ddebe)

this issue is mainly related to below  files
src\team.html
src\Style\_dropdown_menu.css

**Comment by dhavaljprasad** [comment]
Fixed it! Connect me on my Email, I'll explain whats wrong with the code:

Email: nimisha25dhaval@gmail.com

**Comment by Aryan-81** [comment]
Well thanks for fixing .
but i put this intentionally because of my friends

and this website is in its very first starting step and i only going to use basic stack (html , css, javascript) for frontend so code going to be little bit confusing and big.

Still you want to contribute you can create a issue of your own and add pull request , I will consider it a big help .
